changelog:
  categories:
    - title: Bufix
      labels:
        - fix
    - title: New feature
      labels:
        - new
    - title: Changed
      labels:
        - update
    - title: Removed
      labels:
        - remove

